import nodemailer from 'nodemailer';

export interface EmailOptions {
  to: string;
  subject: string;
  html?: string;
  text?: string;
}

class EmailService {
  private transporter: nodemailer.Transporter | null = null;

  /**
   * Initialize the email transporter
   */
  private getTransporter(): nodemailer.Transporter {
    if (!this.transporter) {
      // Use SendGrid SMTP or fallback to console logging in development
      if (process.env.SENDGRID_API_KEY || process.env.SMTP_HOST) {
        this.transporter = nodemailer.createTransporter({
          host: process.env.SMTP_HOST || 'smtp.sendgrid.net',
          port: parseInt(process.env.SMTP_PORT || '587'),
          secure: process.env.SMTP_SECURE === 'true',
          auth: {
            user: process.env.SMTP_USER || 'apikey',
            pass: process.env.SMTP_PASS || process.env.SENDGRID_API_KEY,
          },
        });
      } else {
        // Development mode - log emails to console
        this.transporter = nodemailer.createTransport({
          streamTransport: true,
          newline: 'unix',
          buffer: true,
        });
      }
    }

    return this.transporter;
  }

  /**
   * Send an email
   */
  async sendEmail(options: EmailOptions): Promise<boolean> {
    try {
      const transporter = this.getTransporter();

      const mailOptions = {
        from: process.env.EMAIL_FROM || 'noreply@solosuccess.ai',
        to: options.to,
        subject: options.subject,
        html: options.html,
        text: options.text,
      };

      const info = await transporter.sendMail(mailOptions);

      if (process.env.NODE_ENV === 'development') {
        console.log('Email sent (development mode):', {
          to: options.to,
          subject: options.subject,
          messageId: info.messageId,
        });
      }

      return true;
    } catch (error) {
      console.error('Error sending email:', error);
      return false;
    }
  }

  /**
   * Send intelligence briefing email
   */
  async sendIntelligenceBriefing(
    to: string,
    briefingHtml: string,
    briefingText: string,
    period: string
  ): Promise<boolean> {
    return this.sendEmail({
      to,
      subject: `🕵️ Your ${period} Intelligence Briefing - SoloSuccess AI`,
      html: briefingHtml,
      text: briefingText,
    });
  }

  /**
   * Send competitor alert email
   */
  async sendCompetitorAlert(
    to: string,
    competitorName: string,
    activityTitle: string,
    activityDescription: string,
    sourceUrl?: string
  ): Promise<boolean> {
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #fc8181 0%, #f56565 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 30px; }
    .header h1 { margin: 0; font-size: 24px; }
    .alert { background: #fff5f5; border-left: 4px solid #fc8181; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
    .competitor { color: #667eea; font-weight: 600; font-size: 18px; margin-bottom: 10px; }
    .activity-title { font-size: 16px; font-weight: 600; color: #2d3748; margin-bottom: 10px; }
    .activity-description { color: #4a5568; margin-bottom: 15px; }
    .button { display: inline-block; background: #667eea; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 600; }
    .footer { text-align: center; color: #a0aec0; font-size: 12px; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚨 Critical Competitor Alert</h1>
  </div>

  <div class="alert">
    <div class="competitor">${competitorName}</div>
    <div class="activity-title">${activityTitle}</div>
    <div class="activity-description">${activityDescription}</div>
    ${sourceUrl ? `<a href="${sourceUrl}" class="button">View Details →</a>` : ''}
  </div>

  <div class="footer">
    <p>This alert was automatically generated by SoloSuccess AI</p>
    <p>To manage your alert settings, visit your dashboard</p>
  </div>
</body>
</html>
`;

    const text = `
CRITICAL COMPETITOR ALERT

Competitor: ${competitorName}
Activity: ${activityTitle}

${activityDescription}

${sourceUrl ? `View details: ${sourceUrl}` : ''}

---
This alert was automatically generated by SoloSuccess AI
`;

    return this.sendEmail({
      to,
      subject: `🚨 Critical Alert: ${competitorName} - ${activityTitle}`,
      html,
      text,
    });
  }
}

// Export singleton instance
export const emailService = new EmailService();
