'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { AlertTriangle, Check, ExternalLink, Scale } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { useAcceptDisclaimer } from '@/lib/hooks/useDocumentGeneration';
import { getJurisdictionCustomization } from '@/lib/utils/jurisdiction-customization';

interface LegalDisclaimerProps {
  documentId: string;
  documentType: string;
  jurisdiction?: string;
  isAccepted: boolean;
  onAccept?: () => void;
}

export function LegalDisclaimer({
  documentId,
  documentType,
  jurisdiction,
  isAccepted,
  onAccept
}: LegalDisclaimerProps) {
  const [showFullDisclaimer, setShowFullDisclaimer] = useState(false);
  const [hasReadDisclaimer, setHasReadDisclaimer] = useState(false);
  const acceptDisclaimer = useAcceptDisclaimer();

  const jurisdictionInfo = jurisdiction ? getJurisdictionCustomization(jurisdiction) : null;

  const handleAccept = async () => {
    try {
      await acceptDisclaimer.mutateAsync(documentId);
      if (onAccept) onAccept();
    } catch (error) {
      console.error('Error accepting disclaimer:', error);
    }
  };

  if (isAccepted) {
    return (
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="backdrop-blur-xl bg-green-500/10 border border-green-500/30 rounded-2xl p-4"
      >
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-green-500/20">
            <Check className="w-5 h-5 text-green-400" />
          </div>
          <div>
            <h4 className="font-semibold text-green-300">Disclaimer Accepted</h4>
            <p className="text-sm text-green-400/80">
              You acknowledged this document is for informational purposes only
            </p>
          </div>
        </div>
      </motion.div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="backdrop-blur-xl bg-yellow-500/10 border border-yellow-500/30 rounded-2xl overflow-hidden"
    >
      {/* Warning Header */}
      <div className="bg-gradient-to-r from-yellow-500/20 to-orange-500/20 p-6 border-b border-yellow-500/30">
        <div className="flex items-start gap-4">
          <div className="p-3 rounded-xl bg-yellow-500/20 backdrop-blur-sm">
            <AlertTriangle className="w-6 h-6 text-yellow-400" />
          </div>
          <div className="flex-1">
            <h3 className="text-xl font-bold text-yellow-300 mb-2">
              Important Legal Disclaimer
            </h3>
            <p className="text-yellow-200/80 text-sm">
              Please read and acknowledge this disclaimer before using this document
            </p>
          </div>
        </div>
      </div>

      {/* Disclaimer Content */}
      <div className="p-6 space-y-4">
        {/* Main Disclaimer */}
        <div className="space-y-3">
          <div className="flex items-start gap-3">
            <Scale className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-1" />
            <div>
              <h4 className="font-semibold text-white mb-2">Not Legal Advice</h4>
              <p className="text-gray-300 text-sm leading-relaxed">
                This document is generated by AI and is provided for informational purposes only. 
                It does not constitute legal advice and should not be relied upon as such. The 
                information contained in this document may not be suitable for your specific 
                situation and may not comply with all applicable laws in your jurisdiction.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3">
            <Scale className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-1" />
            <div>
              <h4 className="font-semibold text-white mb-2">Professional Review Required</h4>
              <p className="text-gray-300 text-sm leading-relaxed">
                We strongly recommend that you have this document reviewed by a qualified attorney 
                licensed to practice in your jurisdiction before using it. Legal requirements vary 
                by location and situation, and only a licensed attorney can provide advice tailored 
                to your specific circumstances.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3">
            <Scale className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-1" />
            <div>
              <h4 className="font-semibold text-white mb-2">No Attorney-Client Relationship</h4>
              <p className="text-gray-300 text-sm leading-relaxed">
                Use of this service and any documents generated do not create an attorney-client 
                relationship. We are not a law firm and do not provide legal services or 
                representation.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3">
            <Scale className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-1" />
            <div>
              <h4 className="font-semibold text-white mb-2">Use at Your Own Risk</h4>
              <p className="text-gray-300 text-sm leading-relaxed">
                You use this document at your own risk. We make no warranties or representations 
                about the accuracy, completeness, or suitability of this document for any purpose. 
                We are not liable for any damages arising from your use of this document.
              </p>
            </div>
          </div>
        </div>

        {/* Jurisdiction-Specific Warnings */}
        {jurisdictionInfo && jurisdictionInfo.warnings.length > 0 && (
          <div className="mt-6 p-4 rounded-xl bg-orange-500/10 border border-orange-500/30">
            <h4 className="font-semibold text-orange-300 mb-3 flex items-center gap-2">
              <AlertTriangle className="w-4 h-4" />
              {jurisdictionInfo.jurisdiction}-Specific Considerations
            </h4>
            <ul className="space-y-2">
              {jurisdictionInfo.warnings.map((warning, index) => (
                <li key={index} className="text-sm text-orange-200/80 flex items-start gap-2">
                  <span className="text-orange-400 mt-1">•</span>
                  <span>{warning}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Professional Resources */}
        <div className="mt-6 p-4 rounded-xl bg-blue-500/10 border border-blue-500/30">
          <h4 className="font-semibold text-blue-300 mb-3">Find Professional Legal Help</h4>
          <p className="text-sm text-blue-200/80 mb-3">
            We recommend consulting with a qualified attorney. Here are some resources:
          </p>
          <div className="space-y-2">
            <a
              href="https://www.avvo.com"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 text-sm text-blue-400 hover:text-blue-300 transition-colors"
            >
              <ExternalLink className="w-4 h-4" />
              Avvo - Find a Lawyer
            </a>
            <a
              href="https://www.martindale.com"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 text-sm text-blue-400 hover:text-blue-300 transition-colors"
            >
              <ExternalLink className="w-4 h-4" />
              Martindale-Hubbell - Attorney Directory
            </a>
            {jurisdiction === 'US' && (
              <a
                href="https://www.americanbar.org/groups/legal_services/flh-home/"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-2 text-sm text-blue-400 hover:text-blue-300 transition-colors"
              >
                <ExternalLink className="w-4 h-4" />
                American Bar Association - Free Legal Help
              </a>
            )}
          </div>
        </div>

        {/* Acceptance */}
        <div className="mt-6 pt-6 border-t border-yellow-500/30">
          <label className="flex items-start gap-3 cursor-pointer group">
            <input
              type="checkbox"
              checked={hasReadDisclaimer}
              onChange={(e) => setHasReadDisclaimer(e.target.checked)}
              className="mt-1 w-5 h-5 rounded border-2 border-yellow-500/50 bg-transparent checked:bg-yellow-500 checked:border-yellow-500 focus:ring-2 focus:ring-yellow-500/50 transition-all cursor-pointer"
            />
            <span className="text-sm text-gray-300 group-hover:text-white transition-colors">
              I understand and acknowledge that this document is not legal advice and that I should 
              consult with a qualified attorney before using it. I agree to use this document at my 
              own risk.
            </span>
          </label>

          <div className="mt-4 flex justify-end">
            <Button
              onClick={handleAccept}
              disabled={!hasReadDisclaimer || acceptDisclaimer.isPending}
              className="min-w-[200px]"
            >
              {acceptDisclaimer.isPending ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin mr-2" />
                  Accepting...
                </>
              ) : (
                <>
                  <Check className="w-4 h-4 mr-2" />
                  Accept & Continue
                </>
              )}
            </Button>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
